title: Sebastian Coles
email: sebastian@scoles-advisory.com
description: >- 
  CISO Consultant | Helping organisations delivery great products & services securely, and at speed.
baseurl: ""
url: "https://www.scoles-advisory.com"
github_username:  sebcoles
google_analytics: G-TJCWV11W4Q
tiles-source: pages
tiles-count: 6
socials:
  GitHub: https://github.com/sebcoles
  LinkedIn: https://www.linkedin.com/in/sebastiancoles
markdown: kramdown
sass:
  style: compressed

